### ISSUE TITLE
Add PyAlembic build support

### ISSUE THREAD

**Issue by noizfactory** [GafferHQ/dependencies#123]
As per this [thread](https://groups.google.com/d/msg/gaffer-dev/gXAVEh1Jcxc/yrTgdXXfBQAJ), I'm adding the support for building alembic python bindings in dependencies.

**Comment by johnhaddon** [comment]
Fixed by #124 - closing.

Sachin, for future reference you might like to know that there's a nice feature of GitHub that will auto-close issues if you include a "Fixes #124" comment in your commit message. It's quite neat, because the issues all auto-close when your PR is merged.

**Comment by noizfactory** [comment]
Thanks for the tip John! Will surely use it the next time :)
