### ISSUE TITLE
Required build dependency - libbz2

### ISSUE THREAD

**Issue by HughMacdonald** [GafferHQ/dependencies#14]
I'm not sure where you stand with regards to what level of library you expect to be installed and what you want to include with the dependencies.

I realised that libbz2-dev was required to be installed centrally to get Boost to compile. libbz2 itself was installed already, but not the headers.

**Comment by johnhaddon** [comment]
I'm not sure where I stand either - the idea with this project is to make it as painless as possible to get up and running with Gaffer, but for most folks I think the binaries are sufficient (and preferable). I guess we just need to decide whether on balance it's easier to maintain yet another library in here, or easier to require the installation of the bz2 headers.

What did the error you encountered look like? Was it fairly self explanatory? If so, I'm tempted to call this a "won't fix" for now.

**Comment by HughMacdonald** [comment]
It failed on this line:

https://github.com/GafferHQ/dependencies/blob/c1939c71ccccbc0e404b209083ff084ffc38010f/boost_1_55_0/libs/iostreams/src/bzip2.cpp#L20

Interestingly, having searched for and found the line, the line under it would have been more helpful. I was searching for "bzip", "bzip2", but the comments under it would have been more helpful!

I would agree with you about not doing anything about this - I just wanted to flag that it would be something that people would need to install themselves.

**Comment by johnhaddon** [comment]
OK, I've taken this as an opportunity to update the [README](https://github.com/GafferHQ/dependencies/blob/master/README.md), and mentioned the libbz2 requirement.
