### ISSUE TITLE
Qt.py Upgrades

### ISSUE THREAD

**Issue by bradleyhenke** [GafferHQ/dependencies#145]
The current version of Qt.py is set to 1.1.0.b which was released on August 10, 2017. Given the significant python3 changes which are on the horizon, I was curious if now would be a good opportunity to upgrade this to the latest version 1.2.5. 

There are some improvements to the QtCompat module which may be of value. For example, `QtCompt.wrapInstance` and `QtCompat.getCppPointer` (I realize that there has been some treatment of this in gaffer already), `QtCompat.loadUi()`, and a bunch of other fixes and updates.

**Comment by johnhaddon** [comment]
Yes, I needed to update to 1.2.5 for Qt 5.12, so I'll be making a PR with this in soon. My plan was just to do this on master, where all the Python 3 work is happening, and which all being well will become the dependencies for Gaffer 0.58. I want to treat the `1_maintenance` branch much more conservatively so we don't introduce much change in the Gaffer 0.57 series. Does that sound OK?

**Comment by bradleyhenke** [comment]
Fantastic. I'm glad to hear that it's on the radar. Thanks!

**Comment by johnhaddon** [comment]
Closing - the upgrade to 1.2.5 has been merged and will be included in the 2.0.0 version of the dependencies, which we anticipate shipping in Gaffer 0.59.
