### ISSUE TITLE
OIIO upgrade?

### ISSUE THREAD

**Issue by HughMacdonald** [GafferHQ/dependencies#16]
Hi John,

I heard back from Larry about the OIIO/OSL issue that I came up against. It sounds like OIIO doesn't work with OSL <= 1.7.2, but would work with OSL 1.7.3 or 1.7.4

What do you think of upgrading OSL to 1.7.4 (hopefully not breaking anything in Gaffer) and at the same time upgrading OIIO to 1.7.7?

I can try to get a full dependencies build with these in built towards the end of this week, although I was still finding it falling over on the Qt part of the build. There may be some parts of Gaffer that the OIIO upgrade breaks, so I can make time to look at them once I've got dependencies to build against.

Thanks

**Comment by johnhaddon** [comment]
Sounds fine to me - we should check with @andrewkaufman as far as the specific timing goes though...

**Comment by andrewkaufman** [comment]
As long as its paired with a major version I think we're ok to do it.

**Comment by boberfly** [comment]
I did run into this when building OSL on windows, missing symbols from OIIO and couldn't link...

**Comment by johnhaddon** [comment]
Closing - we're now on OSL1.9.9 and OIIO 1.8.12.
