### ISSUE TITLE
Python 3.7 build on Ubuntu 20.04 is after libffi.so.6

### ISSUE THREAD

**Issue by boberfly** [GafferHQ/dependencies#163]
Hey all,

I was trying to build & run the Python3.7 variant of Gaffer when I got a bit of a stumble, using [this](https://github.com/GafferHQ/dependencies/releases/download/2.0.0a5/gafferDependencies-2.0.0-Python3-linux.tar.gz) as a base:
```
Traceback (most recent call last):
  File "/home/alex/dev/gaffer-build-py3/bin/__gaffer.py", line 55, in <module>
    import IECore
  File "/home/alex/dev/gaffer-build-py3/python/IECore/__init__.py", line 53, in <module>
    __import__( "sys" ).getdlopenflags() | __import__( "ctypes" ).RTLD_GLOBAL
  File "/home/alex/dev/gaffer-build-py3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
```

Perhaps this lib needs copying out of CentOS 7? Ubuntu comes with `libffi.so.7` instead. Python 2.7 works fine on this setup.

**Comment by boberfly** [comment]
Just to confirm I downloaded:
`http://mirror.centos.org/centos/7/os/x86_64/Packages/libffi-3.0.13-19.el7.x86_64.rpm`
And just extracted the .so/symlink into `gaffer-build-py3/lib/` and it works fine.

**Comment by johnhaddon** [comment]
Thanks for the heads up Alex. It looks like Python 2.7 used to bundle libffi with its source, but 3.7 requires it to be on the system. We were getting lucky that it happened to be in our Docker image, but unlucky that the version there doesn't match yours. I think we'll need to build libffi by `./build.py` so we can ensure we have the same version on all platforms.
