### ISSUE TITLE
Update USD to 21.02

### ISSUE THREAD

**Issue by johnhaddon** [GafferHQ/dependencies#181]
Don't build with Ar2 yet though.

**Comment by andrewkaufman** [comment]
Curious if this is urgent for a particular feature or you're just wanting to stay relatively up to date?

**Comment by johnhaddon** [comment]
It was requested by the team working on USD at Cinesite, and I believe it's mostly just about staying up to date.

**Comment by andrewkaufman** [comment]
Gotcha. Its probably worth mentioning to them that it might conflict with AtomsGaffer.

**Comment by johnhaddon** [comment]
Can you elaborate? Is it because Atoms itself links to USD (what version?) or because AtomsGaffer does?

**Comment by andrewkaufman** [comment]
Yes because Atoms links to USD, they're currently using the same as us 20.11

**Comment by johnhaddon** [comment]
Requires https://github.com/ImageEngine/cortex/pull/1134.
