### ISSUE TITLE
[feat] Add arch to archive name

### ISSUE THREAD

**Issue by melMass** [GafferHQ/dependencies#217]
Hi,

I was about to look into building Gaffer/Cortex from source for arm64 Mac when I realised the latest "release" of the deps exist for macOS and from what I can tell they are arm64 builds (which in my case is great), I think it would make sense to specify it in the archive name to make it clear, or to provide universal builds maybe?

Thanks

**Comment by murraystevenson** [comment]
Now that we've resumed publishing arm64 macOS dependencies releases with [9.0.0a1](https://github.com/GafferHQ/dependencies/releases/tag/9.0.0a1), we've started to automatically append "arm64" to the end of the package name when the dependencies release is built on CI.
