### ISSUE TITLE
Colon in a file really irritates git on windows

### ISSUE THREAD

**Issue by boberfly** [GafferHQ/dependencies#44]
Hey John,

Super simple but I can't PR this on Windows very well, but this file here:
https://github.com/GafferHQ/dependencies/blob/master/pyside-setup-6d8dee0/wiki/My-Practice:-Porting-python-scripts-to-PySide2.md

Can you just remove the colon in the file or just delete it? Cheers!

**Comment by johnhaddon** [comment]
I've removed it in PR #47. GitHub's web UI actually let's you edit/delete files and make a PR, so that might be an option for you in the future if you don't have a Linux box to hand...
Cheers...
John
