### ISSUE TITLE
pyside download redirect causing failure?

### ISSUE THREAD

**Issue by ericmehl** [GafferHQ/dependencies#86]
Working on making sure my Windows updates to the dependencies still build on Linux and I'm finding that the build of Pyside on master is failing because the current download url redirects to another url that curl doesn't follow by default.

I'm building on Linux instead of CentOS so maybe CentOS curl follows redirects by default? Or are your builds using wget instead of curl? 

Curious that the main PySide project doesn't have any notes on this either, so I'm wondering if I'm going astray somewhere.

My simple fix is to add the -L switch (follow redirects) to the curl downloader in the ez_setup.py script which solves it just fine.

I'm happy to make a PR along with my Windows changes (coming soon!) but figured I'd check here first since it seems odd I'm the first person running into this problem.

**Comment by johnhaddon** [comment]
Hey Eric,
I thought I had fixed this in https://github.com/GafferHQ/dependencies/pull/84, and that is merged to master and included in release 0.46. It sounds like I did the exact same thing as you too, so I'm surprised that master doesn't work for you...
Cheers...
John

**Comment by ericmehl** [comment]
You are exactly right, I had been working off the wrong master and hadn't brought your changes into my fork yet. Thanks for pointing that out.

Nothing to see here, carry on...
