### ISSUE TITLE
Request: Include Sphinx and sphinx-rtd-theme

### ISSUE THREAD

**Issue by medubelko** [GafferHQ/dependencies#92]
Requesting the addition of vanilla 

* Sphinx (at least 1.4)
* sphinx_rtd_theme (the latest version possible)

to Dependencies, instead of having users download Sphinx (I believe sphinx-rtd-theme 1.0.9 is downloaded during build).

Public users are instructed to grab any version Sphinx, while IE uses a static version. This could cause minor inconsistencies between IE documentation builds and public builds. And Sphinx-rtd-theme 1.0.9 is quite old.

### Advantages ###

* One less package for users to download on their own
* Guaranteed consistency between IE, other studios using Gaffer, and public users
* Some theme features from newer RTD that documentation could use

**Comment by johnhaddon** [comment]
What do we think to this @themissingcow? More of a build environment thing?

**Comment by themissingcow** [comment]
> What do we think to this @themissingcow? More of a build environment thing?

Its build env to me, as we don't include inkscape, scons, etc. either..

**Comment by themissingcow** [comment]
Especially as we now have the docker container, which has everything you need to get going.

**Comment by johnhaddon** [comment]
OK - closing.
